### ISSUE TITLE
gitStream workflow is failing

### ISSUE THREAD

**Issue by yakirm-cr** [linear-b/gitstream#45]
**Describe the bug**

gitStream is failing for all PRs with the following error:

![image](https://user-images.githubusercontent.com/86773995/224685032-ec3cdd5c-c2eb-4fc5-9a3e-d7b30e7673b5.png)

**To Reproduce**

1. Open a PR for in a repository with the default `.github/workflows/gitstream.yml` and `.cm/gitstream.cm`

**Expected behavior**

gitStream workflow should pass. :slightly_smiling_face:

**Comment by gokulk16** [comment]
same error. Also, this failure has blocked our merges since we have other workflows for it.  Please help.
<img width="1054" alt="Screenshot 2023-03-13 at 17 28 09" src="https://user-images.githubusercontent.com/8376313/224695615-a6496599-08e7-4fb9-9589-89dfc845b3cb.png">

We were trying gitstream today and got into this error. 😞

**Comment by vim-zz** [comment]
All good now, we had a regression due to new fearture we are pushing - [org level automation](https://github.com/linear-b/gitstream/issues/26)

**Comment by yakirm-cr** [comment]
@vim-zz Thanks for the prompt response!
Confirmed - we are no longer facing the issue.
